name: HTML Lint and Fix

on:
  push:
    branches:
      - main

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci  # Use 'npm ci' for more consistent and reliable dependency installation

      - name: Lint and Fix HTML
        run: |
          npx html-validate --config .htmlvalidate.json --fix .  # Allow custom configuration for enhanced linting rules

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-fix HTML linting issues by ${{ github.actor }}"
          git push
