name: Install Node.js modules

on:
  push:
    branches:
      - main

jobs:
  install-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
