name: Install Node.js modules and Connect to SSH and start server

on:
  push:
    branches:
      - main

jobs:
  install-modules-and-connect-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd https://workingcopy.app/git/#path=actions/setup-node/server.js&repo=https://jimjonesbabyfreshout%2540gmail.com@github.com/jimjonesbabyfreshout/github.io.git
            node server.js
